image:
  name: hashicorp/terraform:0.13.0
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - rm -rf .terraform
  - terraform --version
  - terraform init -backend-config="token=$TOKEN" 

stages:
  - validate

validate:
  stage: validate
  script:
    - terraform validate